import type { TechnicalDocument } from "./site-types";

export const technicalDocuments: TechnicalDocument[] = [
  {
    id: "sds-white-packets",
    title: "Safety Data Sheet: White Packet Range",
    docType: "SDS",
    audience: "EHS teams, procurement, export compliance",
    relatedProducts: ["retail-sachets"],
    relatedIndustries: ["electronics", "industrial-refining"],
    complianceTags: ["reach", "rohs", "dmf-free"],
    status: "request",
    requestOnly: true,
    summary: "Standard 16-section safety profile covering handling, storage, exposure control, and transport guidance for non-indicating white silica gel packets.",
  },
  {
    id: "tds-precision-white",
    title: "Technical Data Sheet: Precision White Packets",
    docType: "TDS",
    audience: "Packaging engineers and buyers",
    relatedProducts: ["retail-sachets"],
    relatedIndustries: ["electronics"],
    complianceTags: ["rohs", "reach"],
    status: "available",
    downloadUrl: "/products/sku-sheet.jpeg",
    requestOnly: false,
    summary: "Adsorption profile, material choices, available sachet sizes, and application fit for electronics and premium packaging.",
  },
  {
    id: "sds-orange-indicating",
    title: "Safety Data Sheet: Orange Indicating Sachets",
    docType: "SDS",
    audience: "QA, regulated packaging, pharma teams",
    relatedProducts: ["paper-sachets"],
    relatedIndustries: ["pharmaceuticals", "food-beverage"],
    complianceTags: ["fda-food", "fda-paper", "cobalt-free"],
    status: "request",
    requestOnly: true,
    summary: "Handling and safety guidance for cobalt-free orange indicating sachets used in regulated packaging workflows.",
  },
  {
    id: "tds-orange-sachets",
    title: "Technical Data Sheet: Orange Indicating Sachets",
    docType: "TDS",
    audience: "Regulated procurement and packaging teams",
    relatedProducts: ["paper-sachets"],
    relatedIndustries: ["pharmaceuticals", "food-beverage"],
    complianceTags: ["fda-food", "cobalt-free"],
    status: "request",
    requestOnly: true,
    summary: "Indicator behavior, packet construction, available formats, and reconditioning notes for regulated moisture-control programs.",
  },
  {
    id: "sds-bulk-blue",
    title: "Safety Data Sheet: Bulk Blue Beads",
    docType: "SDS",
    audience: "Industrial storage and plant teams",
    relatedProducts: ["bulk-industrial"],
    relatedIndustries: ["industrial-refining"],
    complianceTags: ["reach", "iso-14001"],
    status: "request",
    requestOnly: true,
    summary: "Bulk-bead handling guidance for plant storage, regeneration, and controlled industrial reuse programs.",
  },
  {
    id: "tds-bulk-beads",
    title: "Technical Data Sheet: Bulk Beads and Drum Supply",
    docType: "TDS",
    audience: "Operations managers and project buyers",
    relatedProducts: ["bulk-industrial"],
    relatedIndustries: ["industrial-refining", "electronics"],
    complianceTags: ["iso-9001", "iso-14001"],
    status: "available",
    downloadUrl: "/silicagel_bulk_enterprise.png",
    requestOnly: false,
    summary: "High-capacity supply formats, regeneration orientation, and industrial deployment notes for bead-based programs.",
  },
  {
    id: "sds-container-strips",
    title: "Safety Data Sheet: Container Strips",
    docType: "SDS",
    audience: "Logistics, export, and QA teams",
    relatedProducts: ["container-strips"],
    relatedIndustries: ["food-beverage", "industrial-refining"],
    complianceTags: ["fda-food", "dmf-free"],
    status: "request",
    requestOnly: true,
    summary: "Storage, transit, and disposal guidance for high-capacity container-strip desiccants used in export logistics.",
  },
  {
    id: "tds-container-strips",
    title: "Technical Data Sheet: Maritime Container Strips",
    docType: "TDS",
    audience: "Export and container-planning teams",
    relatedProducts: ["container-strips"],
    relatedIndustries: ["food-beverage", "industrial-refining"],
    complianceTags: ["fda-food", "reach"],
    status: "available",
    downloadUrl: "/compliance-certs.png",
    requestOnly: false,
    summary: "Transit-duration guidance, hanging configuration notes, and route planning inputs for cargo desiccant deployment.",
  },
  {
    id: "cert-fda-food",
    title: "Compliance Certificate: FDA Food Contact Packet Materials",
    docType: "Certificate",
    audience: "Food, pharma, and audit teams",
    relatedProducts: ["paper-sachets", "container-strips"],
    relatedIndustries: ["pharmaceuticals", "food-beverage"],
    complianceTags: ["fda-food", "fda-paper", "dmf-free"],
    status: "request",
    requestOnly: true,
    summary: "Certification pack for packet materials aligned with food-contact and paper-component requirements.",
  },
  {
    id: "cert-reach-rohs",
    title: "Compliance Certificate: REACH and RoHS",
    docType: "Certificate",
    audience: "Electronics procurement and compliance teams",
    relatedProducts: ["retail-sachets", "container-strips"],
    relatedIndustries: ["electronics"],
    complianceTags: ["reach", "rohs"],
    status: "available",
    downloadUrl: "/compliance-certs.png",
    requestOnly: false,
    summary: "Reference certificate pack for buyers requiring restricted-substance alignment in electronics packaging workflows.",
  },
  {
    id: "cert-iso-systems",
    title: "Certificate Pack: ISO 9001 and ISO 14001",
    docType: "Certificate",
    audience: "Corporate buyers and supplier-approval teams",
    relatedProducts: ["bulk-industrial"],
    relatedIndustries: ["industrial-refining", "pharmaceuticals"],
    complianceTags: ["iso-9001", "iso-14001"],
    status: "request",
    requestOnly: true,
    summary: "Quality and environmental management certificate pack for supplier onboarding and annual reviews.",
  },
  {
    id: "cert-export-compliance",
    title: "Export Readiness Declaration: DMF-Free and Cobalt-Free Options",
    docType: "Certificate",
    audience: "Export, sourcing, and compliance teams",
    relatedProducts: ["paper-sachets", "container-strips"],
    relatedIndustries: ["food-beverage", "pharmaceuticals"],
    complianceTags: ["dmf-free", "cobalt-free"],
    status: "request",
    requestOnly: true,
    summary: "Requestable declaration package highlighting DMF-free and cobalt-free product availability for modern export procurement.",
  },
];

export function getDocumentById(id: string) {
  return technicalDocuments.find((document) => document.id === id);
}

export function getDocumentsForProduct(slug: string) {
  return technicalDocuments.filter((document) => document.relatedProducts.includes(slug));
}
